spring:
  mail: 
    host: smtp.gmail.com
    username: sistema.cterapias.njesus@gmail.com
    password: milena01
    port: 587
    properties: 
      mail:
        smtp: 
          starttls:
            enable: true
           
  datasource: 
    name: mydb
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: milena01
    
  jpa: 
    show-sql: true
    hibernate: 
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        
server:
  port: 5000
               